"""Bake the original TBS fastback body into a standalone local mesh asset.

Run from any directory: python tools/build_hero_car.py
Dimensions and axle locations match the existing driving/collision model.
No third-party models or Python dependencies are required.
"""
import json
import math
from pathlib import Path

panels = []
stations = [(-2.9, 1.08, 1.04), (-2.65, 1.28, 1.15), (-2.1, 1.55, 1.29),
            (-1.55, 1.54, 1.38), (-.7, 1.32, 1.37), (.45, 1.32, 1.38),
            (1.45, 1.54, 1.39), (2.15, 1.55, 1.35), (2.65, 1.28, 1.25), (2.9, 1.12, 1.15)]

def profile(z, k):
    i = 0
    while i < len(stations)-2 and z > stations[i+1][0]:
        i += 1
    t = (z-stations[i][0])/(stations[i+1][0]-stations[i][0])
    a,b,c,d = [stations[j][k] for j in (max(0,i-1),i,i+1,min(len(stations)-1,i+2))]
    return .5*(2*b+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t)

def grid(name, material, nu, nv, point, flip=False):
    positions, uvs, indices = [], [], []
    for j in range(nv+1):
        for i in range(nu+1):
            positions.extend(round(x, 5) for x in point(i/nu,j/nv))
            uvs.extend((round(i/nu,5),round(j/nv,5)))
            if i<nu and j<nv:
                a=j*(nu+1)+i;b=a+1;c=a+nu+1;d=c+1
                indices.extend((a,b,c,b,d,c) if flip else (a,c,b,b,c,d))
    panels.append(dict(name=name,material=material,position=positions,uv=uvs,index=indices))

def side_point(u,v,side):
    z=-2.9+5.8*v;w=profile(z,1);h=profile(z,2)
    q=min(abs(z-1.75),abs(z+1.75))
    low=max(.45,.52+math.sqrt(max(0,.635**2-q*q))) if q<.635 else .45
    inset=.11-.085*math.sqrt(max(0,1-(q/.635)**2)) if q<.635 else .11
    return (side*(w-inset*(1-u)**2+.017*math.sin(u*math.pi)),low+(h-low)*u,z)

for side in [-1,1]:
    grid('sculpted-flank-'+str(side),'paint',14,160,lambda u,v,s=side:side_point(u,v,s),side>0)
    grid('shoulder-'+str(side),'paint',12,64,
         lambda u,v,s=side:(s*(1.10+(profile(-1.5+3.15*v,1)-1.10)*u),profile(-1.5+3.15*v,2)+.055*math.sin(u*math.pi),-1.5+3.15*v),side<0)

for name,z0,z1 in [('bonnet',-2.9,-1.5),('rear-deck',1.65,2.9)]:
    grid(name,'paint',40,38,lambda u,v,a=z0,b=z1:((u*2-1)*profile(a+(b-a)*v,1),profile(a+(b-a)*v,2)+.055*(1-(u*2-1)**2),a+(b-a)*v))

# A low, curved fastback cabin, with genuinely curved glass surfaces.
grid('roof','roof',32,32,lambda u,v:((u*2-1)*(.98-.045*(2*v-1)**2),2.035+.075*(1-(u*2-1)**2)+.035*math.sin(v*math.pi),-.72+1.45*v))
grid('windshield','glass',32,20,lambda u,v:((u*2-1)*(1.11-.18*v),1.43+.615*v+.04*math.sin(v*math.pi)+.065*(1-(u*2-1)**2)*v,-1.50+.78*v-.065*(1-(u*2-1)**2)*math.sin(v*math.pi)))
grid('rear-glass','glass',32,22,lambda u,v:((u*2-1)*(.94+.17*v),2.045-.61*v+.02*math.sin(v*math.pi)+.065*(1-(u*2-1)**2)*(1-v),.73+.92*v+.035*(1-(u*2-1)**2)*math.sin(v*math.pi)))
for side in [-1,1]:
    def window(u,v,s=side):
        z_bottom=-1.45+3.05*v;z_top=-.68+1.38*v
        return (s*(1.115-.17*u+.018*math.sin(v*math.pi)),1.425+.61*u+.035*math.sin(v*math.pi)*u,z_bottom*(1-u)+z_top*u)
    grid('side-glass-'+str(side),'glass',14,36,window,side>0)

# Rounded nose/tail panels, with separate lower valances at runtime.
for side in [-1,1]:
    grid('end-cap-'+str(side),'paint',40,10,
         lambda u,v,s=side:((u*2-1)*1.11,.96+v*(.08 if s<0 else .19),s*(2.90+.055*(1-(u*2-1)**2))),side<0)

out=Path(__file__).resolve().parents[1]/'assets'/'tbs-fastback-mesh.js'
out.write_text('/* Original TBS fastback mesh; generated by tools/build_hero_car.py. */\nwindow.TBS_FASTBACK_MESH='+json.dumps({'name':'TBS Fastback 063','stations':stations,'panels':panels},separators=(',',':'))+';\n',encoding='utf-8')
print(f'{out.name}: {sum(len(p["position"])//3 for p in panels)} vertices, {sum(len(p["index"])//3 for p in panels)} triangles')
